### PR TITLE
Return MPS compiled library in `get_native_library()`

### PR DESCRIPTION
**Pull request by sealad886**
* the compiled library for MPS is now returned. This allows axolotl to use this alpha version.

### CODE REVIEW

**Comment by Titus-von-Koeller** [comment]
Have you tested this? From what I understand, the MPS implementation is very minimal to non-existent. I might not be completely up to date, the community was still holding off on the backend abstraction being refactored first (we'll do a complete refactor complying to `torch.library` and registering the methods of the backends as custom_ops).

This week, I'm focusing on the runners and making the alpha release pip installable. The refactor stuff comes next.

cc @rickardp

**Comment by Titus-von-Koeller** [comment]
https://huggingface.co/docs/bitsandbytes/main/en/contributing#setup-pre-commit-hooks

**Comment by sealad886** [comment]
Yeah; as soon as I pushed this I realized it didn’t work at all. I’ve spent the last few days looking at the MLX library deeper and realizing that a lot of these functions are actually implemented natively. So need to figure out how much of this is going to be shared/common function calls vs separate code stream for MLX. On Jun 6, 2024, at 09:58, Titus ***@***.***> wrote:﻿
https://huggingface.co/docs/bitsandbytes/main/en/contributing#setup-pre-commit-hooks

**Comment by Titus-von-Koeller** [comment]
Closing this for now. Feel free to open another one.

**Pull request closed without merging**
